const COMETD = 'cometd'
const DEFAULT_VERSION = '49.0'
const REPLAY = 'replay'
const SERVICE_STATE = {
  READY: 'READY',
  STARTED: 'STARTED',
  STOPPED: 'STOPPED',
  RESTARTING: 'RESTARTING',
  UNDEFINED: 'UNDEFINED'
}

Object.seal(SERVICE_STATE)

module.exports = {
  COMETD,
  DEFAULT_VERSION,
  REPLAY,
  SERVICE_STATE
}